BEGIN;

DROP TABLE IF EXISTS catches;
DROP TABLE IF EXISTS baits;
DROP TABLE IF EXISTS tackle;
DROP TABLE IF EXISTS species;
DROP TABLE IF EXISTS trips;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS points;
DROP TABLE IF EXISTS users;

COMMIT;